version: '3.8'

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      pgnodeapp:
        aliases:
          - "postgres"

  app:
    build:
      context: .
    image: nodeapp
    ports:
      - ${PORT}:${PORT}
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=db
      - NODE_ENV=development
    volumes:
      - .:/app
    networks:
      pgnodeapp:
    depends_on:
      - db
    command: sh -c './wait-for db:5432 -- npm run build-start'

volumes:
  db-data:

networks:
  pgnodeapp:
    driver: bridge