version: '3.8'

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ratings-db-data:/var/lib/postgresql/data
    networks:
      ratingapi:
        aliases:
          - "postgres"

  api:
    build:
      context: .
    image: flaskapp
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@db/${DB_DATABASE}
      - FLASK_ENV=development
    volumes:
      - ./:/app:delegated
    networks:
      ratingapi:
    depends_on:
      - db
    command: sh -c ./entrypoint.sh

volumes:
  ratings-db-data:

networks:
  ratingapi:
    driver: bridge