version: '3'

services:
  drupal:
    build: .
    image: jaglas/custom-drupal
    ports:
      - 8080:80
    links:
      - postgres

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=docker
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data: